#!/bin/sh

set -e

case "$1" in
    purge)
        rm -f /etc/nginx/conf.d/brotli.conf
        rm -f /etc/nginx/modules/ngx_http_brotli_filter_module.so
        rm -f /etc/nginx/modules/ngx_http_brotli_static_module.so
        ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
esac

#DEBHELPER#

exit 0
