name: Build and Deploy
on:
  push:
    tags:
      - '**'
jobs:
  Build-And-Deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - ubuntu:bionic
          - ubuntu:focal
          - ubuntu:jammy
          - debian:bullseye
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Login to Docker Registry
        run: docker login "$DOCKER_REGISTRY" -u "$DOCKER_USERNAME" --password-stdin <<< "$DOCKER_PASSWORD"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Launch build script
        env:
          IMAGE: ${{ matrix.image }}
          PLATFORM: ${{ matrix.platform }}
        run: |
          docker run --pull=always --rm -v `pwd`:/build --platform="${PLATFORM}" "${IMAGE}" /build/build.sh
      - name: Deploy to GitHub Releases
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "true"
          PRE_RELEASE: "false"
          CHANGELOG_FILE: "none"
          ALLOW_EMPTY_CHANGELOG: "true"
          TAG_PREFIX_REGEX: ".*"
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: debs/*.deb
      - name: Deploy to GitHub Releases
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "debs/*.deb"
          token: ${{ secrets.GITHUB_TOKEN }}
          omitBodyDuringUpdate: true
      - name: Deploy to packagecloud
        uses: docker://lpenz/ghaction-packagecloud:v0.1
        with:
          user: ${{ secrets.PACKAGECLOUD_USER }}
          repository: ${{ secrets.PACKAGECLOUD_REPO }}/${{ matrix.os }}/${{ matrix.dist }}
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
